# Generated by Django 2.2.2 on 2020-01-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_time',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='class_time',
            name='system',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='class_time',
            name='time',
            field=models.IntegerField(default=1),
        ),
    ]
